remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

title:
Elena<br>
Schulz-Ruhtenberg
#logo
description:
Ph.D. Researcher<br>
<em>Political Science/ Electoral Research</em><br>
ğŸ“ Hertie School of Governance, Berlin<br>
âœ‰ï¸ [e.schulz-ruhtenberg@phd.hertie-school.org](mailto:e.schulz-ruhtenberg@phd.hertie-school.org)

